version: '3.7'

services:
  db:
    restart: always
    image: postgres:13.10
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

  web:
    restart: always
    build: .
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    restart: always
    build: .././frontend
    ports:
      - "80:3000"
    command: npm start
    depends_on:
      - web
