api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonld: ['application/merge-patch+json']
        multipart: ['multipart/form-data'] 

    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
      # The title of the API.
    title: 'MyYoutube'

    # The description of the API.
    description: 'MyApi'

    # The version of the API.
    version: '1.0'
    defaults:
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 5
    collection:
        pagination:
            items_per_page_parameter_name: per_page # Default value
            page_parameter_name: _page