vich_uploader:
    db_driver: orm

    mappings:
        video_mapping:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/public/files'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
